### ISSUE TITLE
有些html打开报错

### ISSUE THREAD

**Issue by nagerenshifou** [channingbreeze/games#3]
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at file:///D:/programme/phaser/public/games/learn/assets/sky.png may not be loaded.

**Comment by channingbreeze** [comment]
需要放到服务器环境才能运行，不能直接本地双机打开。请看教学视频：[新手上路](https://www.phaser-china.com/tutorial-detail-8.html)，环境搭建篇
